#!/usr/bin/env bash

selected=$(find ~/personal -mindepth 1 -maxdepth 1 -type d | fzf)
if [[ -z $selected ]];then
	exit 0
fi

# basename: name of the folder
# tr: replace characters
selected_name=$(basename $selected | tr ":,. " "____")

switch_to() {
	#if tmux does not exists
	if [[ -z "$TMUX" ]]; then
		tmux attach-client -t $selected_name
	else
		tmux switch-client -t $selected_name
	fi
}

if tmux has-session -t=$selected_name 2> /dev/null; then
	switch_to	
	exit 0
fi

# if we arrive here tmux is not running
# so start a new session
tmux new-session -ds $selected_name -c $selected
switch_to	

tmux send-keys -t $selected_name "ready-tmux" ^M

