#!/usr/bin/env bash

selected=$(find ~/personal -mindepth 1 -maxdepth 1 -type d | fzf)

# if selected name is nothing good like ctl-c then just exit
if [[ -z $selected ]];then
	exit 0
fi

# basename: name of the folder
# tr: replace characters
# need to replace some characters that tmux doesn't like
selected_name=$(basename $selected | tr ":,. " "____")

switch_to() {
	if [[ -z "$TMUX" ]]; then
		# not in tmux so attach to the session with the selected name
		tmux attach-session -t $selected_name
	else
		# can't attach to a session in a session
		# so switch to another session with the name selected name
		tmux switch-client -t $selected_name
	fi
}

if tmux has-session -t="$selected_name" 2> /dev/null; then
	switch_to	
	exit 0
fi

# if we arrive here tmux is not running
# so start a new session
tmux new-session -ds $selected_name -c $selected
switch_to	

tmux send-keys -t $selected_name "ready-tmux"
# tmux send-keys -t $selected_name "ready-tmux" ^M
